# Generated by Django 3.0.6 on 2020-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior'), ('manager', 'Manager')], max_length=10)),
                ('commission', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
