# Generated by Django 3.0.6 on 2020-05-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Sales_Rep',
        ),
    ]
