# Generated by Django 3.0.6 on 2020-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200515_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior'), ('manager', 'Manager')], max_length=10)),
                ('commission', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Sales_Rep',
        ),
    ]
