# Generated by Django 3.0.6 on 2020-05-16 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ProductID',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='Order',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 18, 50, 55, 693369)),
        ),
    ]
