# Generated by Django 3.0.6 on 2020-05-16 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200516_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order',
            new_name='List',
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 19, 0, 28, 808331)),
        ),
    ]
