# Generated by Django 3.0.6 on 2020-05-17 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200516_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 0, 46, 27, 843672)),
        ),
    ]
